DROP TABLE IF EXISTS "userslockerfavoris","userslockerpanier","historiquevente","article","users","affiche";

-- contenu des articles disponible du site
CREATE TABLE IF NOT EXISTS "article"(
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "size" INTEGER NOT NULL,
  "price" REAL NOT NULL,
  "visual_0" TEXT,
  "visual_1" TEXT,
  "visual_2" TEXT,
  "visual_3" TEXT,
  "category" TEXT,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);

INSERT INTO "article"("name", "description", "size", "price", "visual_0", "visual_1", "visual_2", "visual_3",  "category") 
VALUES

-- images en caroussel d'affiche
CREATE TABLE IF NOT EXISTS "affiche" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "visual_1" TEXT NOT NULL,
  "visual_2" TEXT NOT NULL,
  "visual_3" TEXT NOT NULL,
  "visual_4" TEXT NOT NULL,
  "visual_5" TEXT NOT NULL,
  "visual_6" TEXT NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);

INSERT INTO "affiche"("name", "visual_1", "visual_2", "visual_3", "visual_4", "visual_5", "visual_6")
VALUES

-- Lsite inscrits
CREATE TABLE IF NOT EXISTS "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" TEXT NOT NULL,
  "password" TEXT NOT NULL,
  "role" TEXT DEFAULT ('user'),
  "name" TEXT,
  "prenom" TEXT,
  "pays" TEXT,
  "ville" TEXT,
  "adresse" TEXT,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz,
  UNIQUE (email),
  UNIQUE (id)
);

INSERT INTO "users"("email", "password", "role", "name", "prenom", "pays", "ville", "adresse")
VALUES

-- historique des ventes
CREATE TABLE IF NOT EXISTS "historiquevente" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INTEGER NOT NULL REFERENCES "users" ("id"),
  "article_id" INTEGER NOT NULL REFERENCES "article" ("id"),
  "name" TEXT NOT NULL,
  "category" TEXT,
  "price" REAL NOT NULL,
  "visual_0" TEXT,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);

INSERT INTO "historiquevente"("user_id", "article_id", "name", "category", "price" , "visual_0")
VALUES

-- PANIER
CREATE TABLE IF NOT EXISTS "userslockerpanier" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INTEGER NOT NULL REFERENCES "users" ("id"),
  "article_id" INTEGER NOT NULL REFERENCES "article" ("id"),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);

INSERT INTO "userslockerpanier"("user_id", "article_id")
VALUES

-- FAVORIS
CREATE TABLE IF NOT EXISTS "userslockerfavoris" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INTEGER NOT NULL REFERENCES "users" ("id"),
  "article_id" INTEGER NOT NULL REFERENCES "article" ("id"),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);

INSERT INTO "userslockerfavoris"("user_id", "article_id")
VALUES

